# Generated by Django 4.2.11 on 2024-06-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_label_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[(0, 'Select Category'), ('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[(0, 'Select Label'), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='p', max_length=2),
        ),
    ]
