# Generated by Django 4.2.11 on 2024-06-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[(0, 'Select Label'), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=2),
        ),
    ]
