# Generated by Django 4.2.11 on 2024-06-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
