# Generated by Django 4.2.11 on 2024-06-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_item_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
    ]
